name: comtest
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.5+5

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc_concurrency: ^0.2.5
  collection: ^1.18.0
  colorize: ^3.0.0
  enough_convert: ^1.6.0
  flutter_barcode_listener: ^0.1.4
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_libserialport: ^0.4.0
#  flutter_secure_storage: ^9.0.0
  get_it: ^7.7.0
  intl: ^0.19.0
  logging: ^1.2.0
  process_run: ^0.14.2
  random_string: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  dart_code_metrics_presets: ^2.12.0
  flutter_lints: ^4.0.0
  husky: ^0.1.7

dependency_overrides:
  intl: ^0.19.0
  js: ^0.7.1


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/text.tpl
    - assets/cpcl.tpl
    - assets/zpl.tpl
    - assets/Tosh01.lbl
    - assets/Tosh02.lbl
    - assets/tosh_cennik.lbl
    - assets/tosh_DataMatrix.lbl
    - assets/tosh_new_price.lbl

    
                                      